# Generated by Django 5.2.2 on 2025-10-09 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(auto_created=True)),
                ('Display_name', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('family', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=350)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='profilePics/')),
                ('lastSeen', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('profile', models.ManyToManyField(to='users.profile')),
            ],
        ),
    ]
