# Generated by Django 5.2.2 on 2025-10-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfileImage',
            field=models.ImageField(blank=True, default='media/user.png', null=True, upload_to='profilePics/'),
        ),
    ]
