# Generated by Django 5.2.2 on 2025-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfileImage',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='profilePics/'),
        ),
    ]
