# Generated by Django 5.2.2 on 2025-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
